# Generated by Django 4.2.7 on 2023-12-01 05:58

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Specify the name of the category.",
                        max_length=128,
                        unique=True,
                        verbose_name="category name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Provide a brief description of the category.",
                        max_length=255,
                        verbose_name="description of category",
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="Upload an icon representing the category for use as a thumbnail.",
                        upload_to="uploads/category-icons",
                        verbose_name="category icon for thumbnail",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Indicate whether the category is published or not.",
                        verbose_name="is category published",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Automatically generated slug based on the category name.",
                        populate_from="name",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Specify the name of the product.",
                        max_length=255,
                        verbose_name="name of product",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Provide a detailed description of the product.",
                        max_length=255,
                        verbose_name="description of product",
                    ),
                ),
                (
                    "og_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="Specify the original price of the product.",
                        max_digits=10,
                        null=True,
                        verbose_name="original price of product",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="Specify the current price of the product.",
                        max_digits=10,
                        null=True,
                        verbose_name="price of product",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Specify the quantity available in stock for this product.",
                        verbose_name="stock quantity",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Indicate whether the product is published or not.",
                    ),
                ),
                (
                    "is_new_arrival",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this product as a new arrival.",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark this product as a featured item.",
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        help_text="Automatically generated slug based on the product name.",
                        populate_from="name",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select the category to which this product belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorized_productitems",
                        to="products.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Product Items",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        help_text="Upload the image for the product.",
                        upload_to="uploads/product-images/",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Specify the alternative text for the image.",
                        max_length=255,
                        verbose_name="alt text of image",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Specifies the preferred order for displaying the product image.",
                        verbose_name="image display order",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Associate this image with a specific product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.productitem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Images",
                "verbose_name_plural": "Product Images",
                "ordering": ["-display_order"],
            },
        ),
    ]
