# Generated by Django 4.2.7 on 2023-12-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="Associate this image with a specific product.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.productitem",
            ),
        ),
    ]
