# Generated by Django 4.2.7 on 2023-12-02 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_productimage_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="images",
            new_name="image",
        ),
    ]
