# Generated by Django 4.2.7 on 2023-12-03 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_rename_images_productimage_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together={("product", "display_order")},
        ),
    ]
