# Generated by Django 4.2.7 on 2023-12-08 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_productimage_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-created"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="productitem",
            options={
                "ordering": ["-created"],
                "verbose_name": "Product",
                "verbose_name_plural": "Product Items",
            },
        ),
    ]
